### ISSUE TITLE
Environment issues?

### ISSUE THREAD

**Issue by StevenZhang904** [yueqis/API-Based-Agent#3]
I wonder what's the sequence of the set up of the environments? After following the instructions in the README and finish   setting up the opendevin, should I proceed with the installation of browser_env from WEBARENA repo? If so, should I activate the webarena conda env when running `bash evaluation/webarena/scripts/run_infer.sh`? Can you clarify on the set up? 

Meanwhile, in the file `evaluation/webarena/prompt.py`, there are a few lines for debugging at the bottom of the file causing errors. 

Thank you.

**Comment by yueqis** [comment]
Thanks for pointing this out! `evaluation/webarena/prompt.py` is corrected now. After following the instructions in the README and finish setting up the opendevin, you should be good to starting evaluation. You don't need to install browser_env from WebArena repo.
